# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber', '5.2'
gem 'capybara', '3.34'
gem 'selenium-webdriver', '3.142.7'
gem 'rspec', '3.10'
gem 'faker', '2.15.1'
gem 'mongo', '2.14'